### ISSUE TITLE
KeyError: 'roformer_v2'

### ISSUE THREAD

**Issue by lili-li-cpu** [Bureaux-Tao/chip2020_relation_extraction#2]
您好呀，我想问问我更新了bert4keras 到0.11.1，为什么还会有KeyError: 'roformer_v2'这样的问题出现呢？

**Comment by wujietao233** [comment]
我也遇到了相同的问题

**Comment by Bureaux-Tao** [comment]
build_transformer_model里的model参数吗？应该是‘roformer_v2’

**Comment by Bureaux-Tao** [comment]
build_transformer_model里的model参数吗？把最新的bert4keras包下载下来，替换掉utils，然后把包里所有bert4keras.xxx改成utils.xxx，本repo里的utils可能是旧版本的bert4keras。看了下最新包的确实是'roformer_v2': RoFormerV2
